spring:
  application:
    name: techefx-eureka-naming-server

server:
  port: ${port:8761}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#eureka:
#  instance:
#    prefer-ip-address: true