spring:
  application:
    name: techefx-product-stock-service
#  sleuth:
#    enabled: true
#  zipkin:
#    enabled: true
#    base-url: ${ZIPKIN_SERVER:http://localhost:9411/}

server:
  port: ${port:8800}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always

